features:
  - name: motion_energy
    encoder: rdse
    min: 0.0
    max: 2.0

  - name: cursor_velocity
    encoder: rdse
    min: 0.0
    max: 2.0

  - name: interaction_density
    encoder: rdse
    min: 0.0
    max: 2.0

  - name: task_variability
    encoder: rdse
    min: 0.0
    max: 1.5

rate_hz: 10

anomaly_smoothing:
  tau: 0.2

spike_detector:
  recent_window: 30
  prior_window: 90
  growth_threshold: 40
